import type { Route } from "next";

/**
 * Shared application types.
 *
 * The shapes below are the *view models* the UI renders. Database rows
 * (`src/types/database.ts`) are mapped onto them in `src/lib/services/mappers.ts`,
 * so components never depend on column names or nullable DB fields directly.
 */

/** A single navigation link rendered in the header, footer or mobile menu. */
export interface NavItem {
  label: string;
  /** Application route. Generated by `next typegen`, so a typo is a type error. */
  href: Route;
}

/** A bundled image (static import) or a remote URL (e.g. Vercel Blob / CDN). */
export type ImageSource = string;

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Public fields of an event. Never contains anything non-public. */
export interface EventSummary {
  id: string;
  slug: string;
  name: string;
  tagline: string | null;
  description: string | null;
  venueName: string;
  venueAddress: string | null;
  city: string;
  state: string | null;
  mapsUrl: string | null;
  heroImageUrl: string | null;
  contactPhone: string | null;
  contactEmail: string | null;
  /** International format, digits only — what the `wa.me` links are built from. */
  whatsappNumber: string | null;
  instagramUrl: string | null;
  facebookUrl: string | null;
  youtubeUrl: string | null;
  /** Up to six lines of opening hours, in the order they should be shown. */
  supportHours: string[];
  currency: string;
}

export type NightStatus = "scheduled" | "sold_out" | "cancelled" | "completed";

/**
 * One night of the festival with its availability.
 *
 * `isFullyBooked` is computed in the database (paid bookings + organiser
 * sold-out flag), so the UI never has to guess or fetch booking rows.
 */
export interface EventNight {
  id: string;
  date: string;
  /** `HH:MM:SS` from Postgres, or null when unset. */
  startTime: string | null;
  endTime: string | null;
  status: NightStatus;
  capacity: number;
  /** Seats the organiser withheld from online sale (gate, crew, sponsors). */
  capacityHeld: number;
  bookedPeople: number;
  remaining: number;
  isFullyBooked: boolean;
  /** False while the organiser has booking closed on this night. */
  isBookingOpen: boolean;
  /** False when the night is sold out, cancelled, finished, or booking is closed. */
  isBookable: boolean;
}

export type PassEnabledState =
  | { enabled: true }
  | { enabled: false; reason: string };

/** One pass type sold for an event. */
export interface PassOption {
  id: string;
  code: string;
  name: string;
  composition: string;
  description: string | null;
  priceInr: number;
  numberOfPeople: number;
  maxPerBooking: number;
  /** Minimum age in years; 0 means no restriction. */
  minAge: number;
  isActive: boolean;
  /** Why the pass cannot be booked, or `{ enabled: true }`. */
  availability: PassEnabledState;
}

export interface EventHighlight {
  id: string;
  title: string;
  description: string | null;
}

export interface EventFeature {
  id: string;
  /** Stable key the UI maps to an icon, e.g. `dj`. Unknown codes fall back. */
  code: string;
  label: string;
  description: string | null;
}

/** A question/answer pair on the contact page's "Questions before booking" list. */
export interface EventFaq {
  question: string;
  answer: string;
}

/**
 * Organiser-edited public copy from the event row's `site_content`.
 *
 * Null/empty means "no override saved": the page falls back to its built-in
 * default copy, so the site can never go blank over a malformed value.
 */
export interface SiteContent {
  /** About-page heading; null → the page's default dynamic title. */
  aboutTitle: string | null;
  /** About-page body paragraph; null → the page's default text. */
  aboutBody: string | null;
  /** About-page checklist; empty → the page's default points. */
  aboutPoints: string[];
  /** Gallery heading (page and home preview); null → the default title. */
  galleryTitle: string | null;
  /** Gallery intro sentence; null → the default description. */
  galleryIntro: string | null;
  /** Contact-page FAQs; empty → the page's default questions. */
  faqs: EventFaq[];
}

/** Everything the public pages need about the featured event, in one call. */
export interface EventBundle {
  event: EventSummary;
  nights: EventNight[];
  passes: PassOption[];
  highlights: EventHighlight[];
  features: EventFeature[];
  content: SiteContent;
}

// -----------------------------------------------------------------------------
// Gallery
// -----------------------------------------------------------------------------

export type MediaType = "image" | "video";

export interface GalleryItem {
  id: string;
  /** The full image: the row's own URL, or the public object built from its key. */
  src: string;
  /** The grid-sized version, when one was stored alongside the full image. */
  thumbnailSrc: string | null;
  alt: string;
  caption: string;
  tag: string;
  mediaType: MediaType;
  /**
   * Pixel size of the stored image, used to reserve space before it loads. Null for
   * rows added before the gallery recorded dimensions, and for externally hosted
   * media.
   */
  width: number | null;
  height: number | null;
}

// -----------------------------------------------------------------------------
// Contact
// -----------------------------------------------------------------------------

export type ContactIcon = "whatsapp" | "phone" | "mail" | "map";

export interface ContactChannel {
  id: string;
  label: string;
  value: string;
  description?: string;
  /** Internal route (`/book`), or `tel:` / `mailto:` / `https:` link. */
  href: string;
  external?: boolean;
  icon: ContactIcon;
}
