import type { Route } from "next";

/**
 * Shared application types.
 *
 * The shapes below are the *view models* the UI renders. Database rows
 * (`src/types/database.ts`) are mapped onto them in `src/lib/services/mappers.ts`,
 * so components never depend on column names or nullable DB fields directly.
 */

/** A single navigation link rendered in the header, footer or mobile menu. */
export interface NavItem {
  label: string;
  /** Application route. Generated by `next typegen`, so a typo is a type error. */
  href: Route;
}

/** A bundled image (static import) or a remote URL (e.g. Supabase Storage). */
export type ImageSource = string;

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Public fields of an event. Never contains anything non-public. */
export interface EventSummary {
  id: string;
  slug: string;
  name: string;
  tagline: string | null;
  description: string | null;
  venueName: string;
  venueAddress: string | null;
  city: string;
  state: string | null;
  mapsUrl: string | null;
  heroImageUrl: string | null;
  contactPhone: string | null;
  contactEmail: string | null;
  currency: string;
}

export type NightStatus = "scheduled" | "sold_out" | "cancelled" | "completed";

/**
 * One night of the festival with its availability.
 *
 * `isFullyBooked` is computed in the database (paid bookings + organiser
 * sold-out flag), so the UI never has to guess or fetch booking rows.
 */
export interface EventNight {
  id: string;
  date: string;
  /** `HH:MM:SS` from Postgres, or null when unset. */
  startTime: string | null;
  endTime: string | null;
  status: NightStatus;
  capacity: number;
  /** Seats the organiser withheld from online sale (gate, crew, sponsors). */
  capacityHeld: number;
  bookedPeople: number;
  remaining: number;
  isFullyBooked: boolean;
  /** False while the organiser has booking closed on this night. */
  isBookingOpen: boolean;
  /** False when the night is sold out, cancelled, finished, or booking is closed. */
  isBookable: boolean;
}

export type PassEnabledState =
  | { enabled: true }
  | { enabled: false; reason: string };

/** One pass type sold for an event. */
export interface PassOption {
  id: string;
  code: string;
  name: string;
  composition: string;
  description: string | null;
  priceInr: number;
  numberOfPeople: number;
  maxPerBooking: number;
  /** Minimum age in years; 0 means no restriction. */
  minAge: number;
  isActive: boolean;
  /** Why the pass cannot be booked, or `{ enabled: true }`. */
  availability: PassEnabledState;
}

export interface EventHighlight {
  id: string;
  title: string;
  description: string | null;
}

export interface EventFeature {
  id: string;
  /** Stable key the UI maps to an icon, e.g. `dj`. Unknown codes fall back. */
  code: string;
  label: string;
  description: string | null;
}

/** Everything the public pages need about the featured event, in one call. */
export interface EventBundle {
  event: EventSummary;
  nights: EventNight[];
  passes: PassOption[];
  highlights: EventHighlight[];
  features: EventFeature[];
}

// -----------------------------------------------------------------------------
// Gallery
// -----------------------------------------------------------------------------

export type MediaType = "image" | "video";

export interface GalleryItem {
  id: string;
  src: string;
  thumbnailSrc: string | null;
  alt: string;
  caption: string;
  tag: string;
  mediaType: MediaType;
}

// -----------------------------------------------------------------------------
// Contact
// -----------------------------------------------------------------------------

export type ContactIcon = "whatsapp" | "phone" | "mail" | "map";

export interface ContactChannel {
  id: string;
  label: string;
  value: string;
  description?: string;
  /** Internal route (`/book`), or `tel:` / `mailto:` / `https:` link. */
  href: string;
  external?: boolean;
  icon: ContactIcon;
}
