-- ---------------------------------------------------------------------------
-- Booking flow: customer-facing reference, duplicate protection, atomic create
--
-- The booking step has no payment yet. A booking is created with
--   booking_status = 'pending'  and  payment_status = 'unpaid'
-- ('unpaid' is the schema's "payment not made" state — see the column comment)
-- and is only ever moved to 'paid' after a verified Razorpay signature, which
-- does not exist yet. Nothing in this migration can mark a booking as paid.
--
-- Everything a customer submits is untrusted. Prices, the number of admitted
-- people, capacity and availability are all decided here in the database, so a
-- tampered request can never lower a price or oversell a night.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1. Customer-facing booking reference, e.g. DND202600001
-- ---------------------------------------------------------------------------
-- The sequence (`booking_id_seq`) already exists from the initial schema; only
-- the format changes, from BKYYMM-00001 to DND<year><5 digits>. Uniqueness is
-- enforced by bookings.booking_id.
create or replace function public.generate_booking_id()
returns text
language sql
volatile
as $$
  select 'DND'
    || to_char(now(), 'YYYY')
    || lpad(nextval('public.booking_id_seq')::text, 5, '0');
$$;

comment on function public.generate_booking_id() is
  'Customer-facing booking reference, e.g. DND202600001. Uniqueness is enforced by bookings.booking_id.';

-- ---------------------------------------------------------------------------
-- 2. Duplicate-submission protection
-- ---------------------------------------------------------------------------
-- Every checkout attempt carries a key generated by the browser. Re-sending the
-- same key (double click, retry after a timeout, two tabs) returns the booking
-- that already exists instead of creating a second one.
alter table public.bookings
  add column if not exists idempotency_key text;

comment on column public.bookings.idempotency_key is
  'Opaque key generated per checkout attempt. Unique, so a retried request can never create a second booking.';

create unique index if not exists bookings_idempotency_key_idx
  on public.bookings (idempotency_key)
  where idempotency_key is not null;

-- ---------------------------------------------------------------------------
-- 3. Atomic booking creation
-- ---------------------------------------------------------------------------
-- Called by server code only (service role). It is SECURITY DEFINER so it can
-- insert a booking while RLS still denies every browser insert, and it locks the
-- night row so two concurrent requests cannot both pass the capacity check.
--
-- Rules enforced here, in order:
--   * the night exists, belongs to the event and is 'scheduled'
--   * the pass category exists, belongs to the event and is on sale (is_active)
--   * quantity is a positive integer within the pass category's max_per_booking
--   * the submitted number of people matches quantity x people-per-pass
--   * the night still has capacity for that many people (paid bookings only,
--     exactly like get_event_night_availability)
--   * the price is read from pass_categories and multiplied here — never taken
--     from the caller
--
-- Error protocol for the API layer (SQLSTATE -> meaning):
--   PB001 capacity_unavailable  PB002 night_not_bookable  PB003 pass_not_available
--   PB004 quantity_invalid      PB005 people_mismatch     PB006 night_not_found
create or replace function public.create_pending_booking(
  p_event_id         uuid,
  p_event_date_id    uuid,
  p_pass_category_id uuid,
  p_customer_name    text,
  p_customer_mobile  text,
  p_customer_email   text,
  p_quantity         integer,
  p_number_of_people integer,
  p_idempotency_key  text default null
)
returns table (
  booking_uuid     uuid,
  booking_reference text,
  booking_status   text,
  payment_status   text,
  quantity         integer,
  number_of_people integer,
  subtotal         integer,
  total_amount     integer,
  event_id         uuid,
  event_date_id    uuid,
  event_date       date,
  start_time       time,
  end_time         time,
  pass_category_id uuid,
  pass_name        text,
  pass_composition text,
  currency         text,
  created_at       timestamptz,
  was_existing     boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_night       record;
  v_pass        record;
  v_event       record;
  v_existing    record;
  v_booked      integer;
  v_remaining   integer;
  v_required    integer;
  v_booking_id  uuid;
  v_reference   text;
begin
  -- 3.1 Idempotency: has this attempt already produced a booking?
  if p_idempotency_key is not null and length(btrim(p_idempotency_key)) > 0 then
    select b.id into v_existing
    from public.bookings b
    where b.idempotency_key = btrim(p_idempotency_key);

    if found then
      return query
        select b.id, b.booking_id, b.booking_status, b.payment_status, b.quantity,
               b.number_of_people, b.subtotal, b.total_amount, d.event_id, d.id, d.event_date,
               d.start_time, d.end_time, p.id, p.name, p.composition, e.currency,
               b.created_at, true
        from public.bookings b
        join public.event_dates d on d.id = b.event_date_id
        join public.pass_categories p on p.id = b.pass_category_id
        join public.events e on e.id = d.event_id
        where b.id = v_existing.id;

      return;
    end if;
  end if;

  -- 3.2 Lock the night: concurrent attempts for the same night queue here, so
  -- the capacity read below cannot be stale.
  select d.id, d.event_id, d.event_date, d.status, d.capacity, d.start_time, d.end_time
    into v_night
  from public.event_dates d
  where d.id = p_event_date_id
  for update;

  if not found then
    raise exception 'night_not_found' using errcode = 'PB006';
  end if;

  if v_night.event_id <> p_event_id then
    raise exception 'night_not_found' using errcode = 'PB006';
  end if;

  select e.id, e.name, e.status, e.currency into v_event
  from public.events e
  where e.id = p_event_id;

  if not found or v_event.status <> 'published' then
    raise exception 'night_not_bookable' using errcode = 'PB002';
  end if;

  if v_night.status <> 'scheduled' then
    raise exception 'night_not_bookable' using errcode = 'PB002';
  end if;

  -- 3.3 The pass must belong to this event and be on sale.
  select p.id, p.name, p.composition, p.price_inr, p.number_of_people, p.max_per_booking, p.is_active
    into v_pass
  from public.pass_categories p
  where p.id = p_pass_category_id;

  if not found then
    raise exception 'pass_not_available' using errcode = 'PB003';
  end if;

  if v_pass.is_active is not true then
    raise exception 'pass_not_available' using errcode = 'PB003';
  end if;

  if not exists (
    select 1 from public.pass_categories p
    where p.id = p_pass_category_id and p.event_id = p_event_id
  ) then
    raise exception 'pass_not_available' using errcode = 'PB003';
  end if;

  -- 3.4 Quantity is a positive integer the pass category allows.
  if p_quantity is null or p_quantity < 1 or p_quantity > v_pass.max_per_booking then
    -- detail carries the limit, so the API can say what is allowed.
    raise exception 'quantity_invalid' using errcode = 'PB004', detail = v_pass.max_per_booking::text;
  end if;

  -- 3.5 A pass admits a fixed group, so the submitted head count must match it.
  v_required := p_quantity * v_pass.number_of_people;

  if p_number_of_people is null or p_number_of_people <> v_required then
    -- detail carries the head count this booking must cover.
    raise exception 'people_mismatch' using errcode = 'PB005', detail = v_required::text;
  end if;

  -- 3.6 Capacity, counted the same way as the public availability function:
  -- paid bookings only. A pending booking does not hold a place until it is paid.
  select coalesce(sum(b.number_of_people) filter (where b.payment_status = 'paid'), 0)::integer
    into v_booked
  from public.bookings b
  where b.event_date_id = p_event_date_id;

  v_remaining := greatest(v_night.capacity - v_booked, 0);

  if v_required > v_remaining then
    -- detail carries how many places are actually left.
    raise exception 'capacity_unavailable' using errcode = 'PB001', detail = v_remaining::text;
  end if;

  -- 3.7 Same content, brand-new key inside the double-submit window (a page
  -- reload loses the key): treat it as the same attempt instead of creating a
  -- second booking. Paid or older bookings are never reused.
  select b.id into v_existing
  from public.bookings b
  where b.event_date_id = p_event_date_id
    and b.pass_category_id = p_pass_category_id
    and b.customer_mobile = p_customer_mobile
    and b.quantity = p_quantity
    and b.booking_status = 'pending'
    and b.payment_status = 'unpaid'
    and b.created_at > now() - interval '15 minutes'
  order by b.created_at desc
  limit 1;

  if found then
    return query
      select b.id, b.booking_id, b.booking_status, b.payment_status, b.quantity,
             b.number_of_people, b.subtotal, b.total_amount, d.event_id, d.id, d.event_date,
             d.start_time, d.end_time, p.id, p.name, p.composition, e.currency,
             b.created_at, true
      from public.bookings b
      join public.event_dates d on d.id = b.event_date_id
      join public.pass_categories p on p.id = b.pass_category_id
      join public.events e on e.id = d.event_id
      where b.id = v_existing.id;

    return;
  end if;

  -- 3.8 Insert. number_of_people, subtotal and total_amount are deliberately not
  -- part of the INSERT column list: the set_booking_amounts() trigger computes
  -- all three from pass_categories before the row is written, so money can only
  -- ever come from the database and a price sent by the browser is ignored.
  insert into public.bookings (
    customer_name, customer_mobile, customer_email,
    event_date_id, pass_category_id,
    quantity, booking_status, payment_status, idempotency_key
  )
  values (
    btrim(p_customer_name), p_customer_mobile, p_customer_email,
    p_event_date_id, p_pass_category_id,
    p_quantity, 'pending', 'unpaid',
    nullif(btrim(coalesce(p_idempotency_key, '')), '')
  )
  returning id, bookings.booking_id into v_booking_id, v_reference;

  return query
    select b.id, b.booking_id, b.booking_status, b.payment_status, b.quantity,
           b.number_of_people, b.subtotal, b.total_amount, d.event_id, d.id, d.event_date,
           d.start_time, d.end_time, p.id, p.name, p.composition, e.currency,
           b.created_at, false
    from public.bookings b
    join public.event_dates d on d.id = b.event_date_id
    join public.pass_categories p on p.id = b.pass_category_id
    join public.events e on e.id = d.event_id
    where b.id = v_booking_id;
end;
$$;

comment on function public.create_pending_booking(uuid, uuid, uuid, text, text, text, integer, integer, text) is
  'Creates one pending/unpaid booking atomically: locks the night, re-reads capacity from paid bookings only, reads the price from pass_categories and ignores any client-supplied amount. Service role only — browsers cannot call it.';

revoke all on function public.create_pending_booking(uuid, uuid, uuid, text, text, text, integer, integer, text) from public;
revoke all on function public.create_pending_booking(uuid, uuid, uuid, text, text, text, integer, integer, text) from anon, authenticated;
grant execute on function public.create_pending_booking(uuid, uuid, uuid, text, text, text, integer, integer, text) to service_role;

comment on column public.bookings.payment_status is
  'Payment lifecycle: unpaid -> created (Razorpay order) -> paid | failed | refunded. paid is only ever set after signature verification.';
